library(targets)
library(tarchetypes)
library(quantmod)
library(kableExtra)
library(conflicted)
library(tidyverse)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::arrange)
conflicts_prefer(dplyr::desc)
conflicts_prefer(purrr::map)
conflicts_prefer(purrr::map_dfr)