library(targets)
library(tarchetypes)
library(cqn)
library(biomaRt)
library(GenomicRanges)
library(IRanges)
library(Biostrings)
library(BSgenome.Hsapiens.UCSC.hg38)
library(kableExtra)
library(conflicted)
library(tidyverse)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::count)
conflicts_prefer(base::as.factor)
